# Generated by Django 5.1.4 on 2024-12-12 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
