# Generated by Django 5.1.4 on 2024-12-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0003_remove_event_id_alter_event_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='times',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
