# Generated by Django 5.1.4 on 2024-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0005_eventresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.CharField(default='adam', max_length=255),
            preserve_default=False,
        ),
    ]
